POST http://127.0.0.1:8000/api/v1/auth/registro
Accept: application/json
Content-Type:  application/json

{
    "name":"maria",
    "email": "bernal@gmail.com",
    "password": "bernal123"

}

###login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "micorreo@gmail.com",
    "password":"micontraseña"
}
